development:
  adapter: postgresql
  encoding: unicode
  database: love_development
  pool: 5
  username: JuandGirald
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: love_test
  pool: 5
  username: JuandGirald
  password: 
